version: "3.8"

services:
  
  #mariadb
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    expose:
      - "3306"
    volumes: 
      - db-volume:/var/lib/mysql
    networks:
      - docker-network
    restart: on-failure
    environment:
      HOST_NAME: "${HOST_NAME}"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"

  # wordpress
  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    expose:
      - "9000"
    volumes:
      - wp-volume:/var/www/wordpress
    networks:
      - docker-network
    restart: on-failure
    environment:
      WORDPRESS_DOMAIN_NAME: "${WP_DOMAIN_NAME}"
      WORDPRESS_TITLE: "${WP_TITLE}"
      WORDPRESS_ADMIN_USER: "${WP_ADMIN_USER}"
      WORDPRESS_ADMIN_PWD: "${WP_ADMIN_PWD}"
      WORDPRESS_ADMIN_EMAIL: "${WP_ADMIN_EMAIL}"
      WORDPRESS_USER: "${WP_USER}"
      WORDPRESS_USER_PWD: "${WP_USER_PWD}"
      WORDPRESS_USER_EMAIL: "${WP_USER_EMAIL}"
      WORDPRESS_DB_NAME: "${MARIADB_DATABASE}"
      WORDPRESS_DB_USER: "${MARIADB_USER}"
      WORDPRESS_DB_PASSWORD: "${MARIADB_PASSWORD}"
      WORDPRESS_DB_HOST: "${MARIADB_HOST}"
    depends_on:
      - mariadb

  #nginx
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    ports: 
        - "443:443"
    volumes:
      - wp-volume:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - docker-network
    restart: on-failure

networks:
  docker-network:
    name: docker-network
    driver: bridge

volumes:
  db-volume:
    name: db-volume
    driver_opts:
      o: bind
      type: none
      device: ${HOST_PATH}/mariadb

  wp-volume:
    name: wp-volume
    driver_opts:
      o: bind
      type: none
      device: ${HOST_PATH}/wordpress